[package]
name = "did-parser"
version = "0.1.0"
authors = ["Steve Degosserie <steve@block0.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "^1.0"
regex = "^1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nom = { version="^5", default-features = false, features = ["regex"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
nom = { version="^5", default-features = false, features = ["regex"] }
